# This file configures pre-commit hooks.
# See https://pre-commit.com/ for general information
# See https://pre-commit.com/hooks.html for a listing of possible hooks

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-json
        exclude: "tsconfig.*json"
      - id: check-yaml
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
        exclude_types:
          - svg
          - pofile
        exclude: "(^LICENSE$)"
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: trailing-whitespace
        exclude_types:
          - svg
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.9-for-vscode'
    hooks:
      - id: prettier
        types_or:
          - javascript
          - ts
          - markdown
        exclude: "(^Pipfile\\.lock$)"
  # Python hooks
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.270'
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  # Shell script hooks
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args:
          - "--tab"
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.9.0.5"
    hooks:
      - id: shellcheck
