repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-case-conflict
      - id: check-xml
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: fix-encoding-pragma
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v2.2.3"
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --max-complexity=20
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.8.0.4"
    hooks:
      - id: shellcheck
